spring.application.name=autoescuela
server.port=8081
spring.profiles.active=dev

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.globally_quoted_identifiers=true

spring.jackson.deserialization.fail-on-null-for-primitives=false
spring.jpa.properties.hibernate.cache.use_second_level_cache=false
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

spring.web.error.include-message=always
spring.web.error.include-binding-errors=always
spring.web.error.include-stacktrace=on_param
spring.web.error.include-exception=true